### ISSUE TITLE
Error root cannot be null

### ISSUE THREAD

**Issue by SebGonzalez** [rgielen/javafx-weaver#12]
Hi,

I have an error when i start the demo project : 

`Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException: Root cannot be null
	at javafx.scene.Scene.<init>(Scene.java:345)
	at javafx.scene.Scene.<init>(Scene.java:207)
	at com.eukles.AgenResopost.JavaFxApplication.start(JavaFxApplication.java:29)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	... 1 more
`

I don't know why ? I use Spring boot 2.4.1, JavaFX 15.0.1 and javafx-weawer 1.3.0.
I use the same code than the springboot-starter-sample.

Here is my pom.xml ; 
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.4.1</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.test</groupId>
	<artifactId>SpringBootFxTest</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>SpringBootFxTest</name>
	<description>Test</description>

	<properties>
		<java.version>11</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-controls</artifactId>
			<version>15.0.1</version>
		</dependency>

		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-fxml</artifactId>
			<version>15.0.1</version>
		</dependency>

		<dependency>
			<groupId>net.rgielen</groupId>
			<artifactId>javafx-weaver-spring-boot-starter</artifactId>
			<version>1.3.0</version>
		</dependency>

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<version>2.4.1</version>
			</plugin>
			<plugin>
				<groupId>org.openjfx</groupId>
				<artifactId>javafx-maven-plugin</artifactId>
				<version>0.0.5</version>
				<configuration>
					<mainClass>com.eukles.AgenResopost.JavafxWeaverSpringbootSampleApplication</mainClass>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>

```

Thanks you in advance

**Comment by rgielen** [comment]
Hi,

your issue must be with the actual code of your project. Find attached a adapted sample with basically your settings, works as expected on my side.
[springboot-starter-sample.zip](https://github.com/rgielen/javafx-weaver/files/5797175/springboot-starter-sample.zip)

**Comment by SebGonzalez** [comment]
Thanks you it's work ! I don't know why, i compare the two codes and i don't find any difference. I will start with your example.
Thanks !

**Comment by hasanli-orkhan** [comment]
The reason of this problem is the structure of resources folder.
You need to have the same folder (package) hierarchy like the project.
For example if your MainController in com.example.project.controller package inside of java folder, so your fxml file need placed in com.example.project.controller inside resources folder.
```
java/com.example.project.controller/MainController.java
resources/com.example.project.controller/MainController.fxml
```

**Comment by shramkoaleksey90** [comment]
Thank you a lot, @hasanli-orkhan, I have been looking for more than a week for the same mistake

**Comment by ehsanfirst** [comment]
Thank you @hasanli-orkhan .
you really helped me a lot.
