### ISSUE TITLE
please port it to spring 6 / spring boot 3

### ISSUE THREAD

**Issue by ShulluTech** [rgielen/javafx-weaver#22]
When moving from spring boot 2 (on which it worked fine) to spring boot 3, I got the following error:

java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:893)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'net.rgielen.fxweaver.core.FxWeaver' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:343)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:334)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1249)
	at in.shullu.erp.a1sb3pyr.gui.IruveFxAndSpringBooter.start(IruveFxAndSpringBooter.java:226)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:839)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:483)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:263)
	... 1 more

**Comment by zapek** [comment]
Any more details?

I had to do the following in my project as a workaround:

```java
@Configuration
public class FxWeaverConfiguration
{
    @Bean
    public FxWeaver fxWeaver(ConfigurableApplicationContext applicationContext)
    {
        return new SpringFxWeaver(applicationContext);
    }
}
```

**Comment by zapek** [comment]
I tried to remove my workaround with Spring Boot 3.1.5 and it still doesn't work.

`Parameter 0 of constructor in io.xeres.ui.support.window.WindowManager required a bean of type 'net.rgielen.fxweaver.core.FxWeaver' that could not be found.`

I do have this in my gradle.build:
`implementation 'net.rgielen:javafx-weaver-spring-boot-starter:1.3.0'`

Has FxWeaver been tested with Spring Boot 3? Because it used to work before.

**Comment by ShulluTech** [comment]
> Any more details?
> 
> I had to do the following in my project as a workaround:
> 
> ```java
> @Configuration
> public class FxWeaverConfiguration
> {
>     @Bean
>     public FxWeaver fxWeaver(ConfigurableApplicationContext applicationContext)
>     {
>         return new SpringFxWeaver(applicationContext);
>     }
> }
> ```

Thank you - this addition fixed my problem.

**Comment by ShulluTech** [comment]
> When moving from spring boot 2 (on which it worked fine) to spring boot 3, I got the following error:
>  ....

@zapek's solution above fixed the issue for me.

**Comment by blulic** [comment]
Hi @alok555 @zapek  the above is autoconfiguration issue (which got broken from Spring Boot 3).
I have created PR for https://github.com/rgielen/javafx-weaver/pull/25 which will sort this out, pls see also  #24

**Comment by zapek** [comment]
I [removed](https://github.com/zapek/Xeres/commit/48b627bd28c7b5c0e4947583728eb1f77a0aa599) my workaround from my project and can confirm that everything works fine with FxWeaver 2.0.0 and Spring Boot 3.3.1.

Thanks!
